### PR TITLE
bugfix: firemon: skip coredump if unsupported

### LINKED ISSUE #6414: build: error: ‘PROC_EVENT_COREDUMP’ undeclared (kernel version 3.8)
### Steps to Reproduce

```sh
docker run --platform linux/386 --rm -it satmandu/crewbuild:386
```

Once in docker container:

```sh
# (optional, will speed up commands)
rm -f "$CREW_PREFIX/etc/bash.d/git" "$CREW_PREFIX/etc/bash.d/git-prompt.sh" &&
source ~/.bashrc

# build
cd
git clone https://github.com/netblue30/firejail
cd firejail
autoreconf -fvi
./configure
make
```

Errors:

```
gcc -ggdb -O2 -DVERSION='"0.9.73"' -Wall -Wextra  -Wformat -Wformat-security -fstack-protector-all -DPREFIX='"/usr/local"' -DSYSCONFDIR='"/usr/local/etc/firejail"' -DLIBDIR='"/usr/local/lib"' -DBINDIR='"/usr/local/bin"' -DVARDIR='"/var/lib/firejail"'   -DHAVE_CHROOT -DHAVE_DBUSPROXY -DHAVE_FILE_TRANSFER  -DHAVE_GLOBALCFG   -DHAVE_NETWORK  -DHAVE_OUTPUT  -DHAVE_PRIVATE_HOME   -DHAVE_SUID -DHAVE_USERNS -DHAVE_USERTMPFS -DHAVE_X11 -D_FORTIFY_SOURCE=2 -mindirect-branch=thunk -fstack-clash-protection -fstack-protector-strong -MMD -MP -fPIE -march=i686  -c ../../src/firemon/procevent.c -o ../../src/firemon/procevent.o
../../src/firemon/procevent.c: In function ‘procevent_monitor’:
../../src/firemon/procevent.c:399:38: error: ‘PROC_EVENT_COREDUMP’ undeclared (first use in this function); did you mean ‘PROC_EVENT_COMM’?
  399 |                                 case PROC_EVENT_COREDUMP:
      |                                      ^~~~~~~~~~~~~~~~~~~
      |                                      PROC_EVENT_COMM
../../src/firemon/procevent.c:399:38: note: each undeclared identifier is reported only once for each function it appears in
../../src/firemon/procevent.c:400:66: error: ‘union <anonymous>’ has no member named ‘coredump’
  400 |                                         pid = proc_ev->event_data.coredump.process_tgid;
      |                                                                  ^
make[1]: *** [../../src/prog.mk:25: ../../src/firemon/procevent.o] Error 1
make[1]: Leaving directory '/home/chronos/user/firejail/src/firemon'
make: *** [Makefile:72: src/firemon/firemon] Error 2
```

### Additional context

All i686 chromebooks have a kernel version of 3.8, and it looks like `PROC_EVENT_COREDUMP` was only added in 3.10.

### Environment

- Linux distribution and version: ChromeOS M58

### PR DESCRIPTION
**Pull request by kmk3**
The coredump-related code fails to build on Linux kernel version 3.8 as
apparently it only exists on Linux since version 3.10:

    docker run --platform linux/386 --rm -it satmandu/crewbuild:386
    [...]
    ./configure && make
    [...]
    gcc -ggdb -O2 -DVERSION='"0.9.73"' [...] -march=i686  -c ../../src/firemon/procevent.c -o ../../src/firemon/procevent.o
    ../../src/firemon/procevent.c: In function ‘procevent_monitor’:
    ../../src/firemon/procevent.c:399:38: error: ‘PROC_EVENT_COREDUMP’ undeclared (first use in this function); did you mean ‘PROC_EVENT_COMM’?
      399 |                                 case PROC_EVENT_COREDUMP:
          |                                      ^~~~~~~~~~~~~~~~~~~
          |                                      PROC_EVENT_COMM
    ../../src/firemon/procevent.c:399:38: note: each undeclared identifier is reported only once for each function it appears in
    ../../src/firemon/procevent.c:400:66: error: ‘union <anonymous>’ has no member named ‘coredump’
      400 |                                         pid = proc_ev->event_data.coredump.process_tgid;
          |                                                                  ^
    make[1]: *** [../../src/prog.mk:25: ../../src/firemon/procevent.o] Error 1
    make[1]: Leaving directory '/home/chronos/user/firejail/src/firemon'
    make: *** [Makefile:72: src/firemon/firemon] Error 2

Environment: gcc 14.1.0, glibc 2.23 and linuxheaders 3.8 on ChromeOS
M58.

Misc: @Zopolis4 also reports that "All i686 chromebooks have a kernel
version of 3.8".

This amends commit e11949a71 ("add support for comm, coredump, and prctl
procevents in firemon", 2024-04-30).

Fixes #6414.

Reported-by: @Zopolis4

### CODE REVIEW

**Comment by kmk3** [comment]
@Zopolis4

Does this work?

Also, what is the version of the Linux API headers?

On Arch:

```console
$ pacman -Q linux-api-headers
linux-api-headers 6.8-1
```

**Review by glitsj16 — APPROVED** [review]
LGTM

**Comment by Zopolis4** [comment]
> Does this work?

Yes.

> Also, what is the version of the Linux API headers?

Linux header version:
```
$ crew search -v linuxheaders
linuxheaders: Linux headers for Chrome OS.
https://kernel.org/
Version: 3.8
License: GPL-2
```
