### ISSUE TITLE
Building from git broken on Arch Linux after recent apparmor-related commits

### ISSUE THREAD

**Issue by glitsj16** [netblue30/firejail#1750]
Building from git master is currently broken on Arch Linux. I usually keep up with git master pretty close, but have been out a few days so I'm not sure which exact commit(s) are responsible for this breakage. I assume it might be something in the recent apparmor-related commits. On Ubuntu things are fine, as that has apparmor in its default repositories. But Arch Linux doesn't and this hasn't been a problem before.

Full [configure/make output](https://ptpb.pw/T1er.txt) available.

The below `make` output stays exactly the same, no matter whether configuring with only --prefix=/usr (the default), adding --disable-apparmor or --enable-apparmor=no:

$ make
make -C src/lib
make[1]: Entering directory '/home/glitsj16/.buildzone/00.tmpfs/firejail/src/lib'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/glitsj16/.buildzone/00.tmpfs/firejail/src/lib'
make -C src/firejail
make -C src/firemon
make -C src/fsec-print
make[1]: Entering directory '/home/glitsj16/.buildzone/00.tmpfs/firejail/src/firemon'
gcc  -ggdb  -O2 -DVERSION='"0.9.53"' -DPREFIX='"/usr"'   -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security  -c apparmor.c -o apparmor.o
make[1]: Entering directory '/home/glitsj16/.buildzone/00.tmpfs/firejail/src/fsec-print'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/glitsj16/.buildzone/00.tmpfs/firejail/src/fsec-print'
make[1]: Entering directory '/home/glitsj16/.buildzone/00.tmpfs/firejail/src/firejail'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/glitsj16/.buildzone/00.tmpfs/firejail/src/firejail'
make -C src/fsec-optimize
make -C src/firecfg
make[1]: Entering directory '/home/glitsj16/.buildzone/00.tmpfs/firejail/src/fsec-optimize'
gcc  -ggdb  -O2 -DVERSION='"0.9.53"'  -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/firejail"' -DLIBDIR='"/usr/lib"' -DHAVE_X11 -DHAVE_PRIVATE_HOME  -DHAVE_OVERLAYFS -DHAVE_SECCOMP -DHAVE_GLOBALCFG -DHAVE_SECCOMP_H -DHAVE_CHROOT -DHAVE_NETWORK -DHAVE_USERNS -DHAVE_BIND -DHAVE_FILE_TRANSFER -DHAVE_WHITELIST -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security  -c main.c -o main.o
make[1]: Entering directory '/home/glitsj16/.buildzone/00.tmpfs/firejail/src/firecfg'
gcc  -ggdb  -O2 -DVERSION='"0.9.53"'   -DPREFIX='"/usr"'  -DSYSCONFDIR='"/etc/firejail"' -DLIBDIR='"/usr/lib"' -DHAVE_X11 -DHAVE_SECCOMP -DHAVE_SECCOMP_H -DHAVE_CHROOT -DHAVE_NETWORK -DHAVE_USERNS -DHAVE_BIND -DHAVE_FILE_TRANSFER -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security  -c desktop_files.c -o desktop_files.o
apparmor.c:21:10: fatal error: sys/apparmor.h: No such file or directory
 #include <sys/apparmor.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:23: apparmor.o] Error 1
make[1]: Leaving directory '/home/glitsj16/.buildzone/00.tmpfs/firejail/src/firemon'
make: *** [Makefile:35: src/firemon] Error 2

Regards

**Comment by Fred-Barclay** [comment]
Thanks, yes, this was introduced in 5ebebb1211364a4d7164ad30d021adabf5374d32 (according to my testing). I've pinged @netblue30 with a comment; hopefully we can get it sorted soon. 😄 

I did have trouble even when building on Ubuntu 17.10, though.
Cheers!
Fred

**Comment by netblue30** [comment]
Fixed, thanks!

**Comment by Fred-Barclay** [comment]
Thanks @glitsj16 and @netblue30! 👍
