### ISSUE TITLE
Adding support for musl libc

### ISSUE THREAD

**Issue by Duncaen** [netblue30/firejail#91]
It would be nice if we can get musl libc support for firejail.
We currently have a dirty patch/hack to be able to compile libtrace.

```
# XXX: dirty hack - very limited stdio.h definitions
# to avoid redefinition of intercepted libc functions
# Include our header instead of stdio.h and sys/stat.h
# Use struct stat instead of struct stat64 (they are equal)
sed -i ${wrksrc}/src/libtrace/libtrace.c \
	-e 's;#include <stdio.h>;#include "musl_defs.h";' \
	-e 's;#include <sys/stat.h>;;' \
	-e 's;struct stat64;struct stat;g' 
```
https://github.com/voidlinux/void-packages/blob/master/srcpkgs/firejail/template#L57

And the musl_defs.h file is located here https://github.com/voidlinux/void-packages/blob/master/srcpkgs/firejail/files/musl_defs.h

**Comment by netblue30** [comment]
I have the fix in, add --enable-musl-libc when you ./configure:
`````
$ ./configure --enable-musl-libc --prefix=/usr
`````

**Comment by netblue30** [comment]
Should work fine in 0.9.80
